spring:
  datasource:
    hikari:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbcUrl: jdbc:log4jdbc:mariadb://localhost:3306/test_db2
        username: test_jhjo
        password: '1234'
  jpa:
    username: test_jhjo
    url: jdbc:mariadb://localhost:3306/test_db2?useUnicode=true&characterEncoding=utf-8
    driverClassName: org.mariadb.jdbc.Driver
    password: '1234'
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
mybatis:
  type-aliases-package: com.example.demoapi.model
  mapper-location:
    classpath: com.example.demoapi.xmlfiles/*.xml
server:
  port: '8080'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG
